import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/layout/Footer";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Evaluer vous-même grâce à l'IA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <main className="flex-grow container mx-auto p-4">{children}</main>
        <Footer />
      </AuthProvider>
    </html>
  );
}
